name: Disparar Automacao Pumble

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Faz requisicao para o Apps Script
        run: |
          curl -X POST "https://script.google.com/macros/s/AKfycbwzUFk6zcQxC8XRL1EefWTgh8mCzxbDZC9fvEPbFQOuEZJAfw-XAYrX_s70d_VEDnNxBg/exec" \
          -H "Content-Type: application/json" \
          -d '{
            "codigoAcao": "ACAO-101",
            "nomeQuemFez": "Daniele",
            "numeroSei": "SEI-080002/021268/2026",
            "atividadeRealizada": "Análise de Processo SEI"
          }'
